services:
  bridge:
    profiles: ["bridge"]
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    command: /bin/bash -lc "while sleep 1000; do :; done"
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BASE_IMAGE: osrf/ros:humble-desktop-full
        USERNAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}
    image: go2-lab:bridge
    container_name: bridge
    network_mode: "host"

  jetson:
    profiles: ["jetson"]
    platform: linux/arm64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BASE_IMAGE: althack/ros2:humble-full
        USERNAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}
      network: host
    image: go2-lab:jetson
    container_name: jetson
    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: "host"
    shm_size: "4gb"
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "all"
      NVIDIA_VISIBLE_DEVICES: "all"
      DISPLAY: ${DISPLAY}
      RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
      ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-0}"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
      - /data/LIDAR_dataset:/home/${USER}/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: /bin/bash -lc "while sleep 1000; do :; done"
