ARG BASE_IMAGE=althack/ros2:humble-full
FROM ${BASE_IMAGE}
ENV DEBIAN_FRONTEND=noninteractive

USER root

COPY configs/deps/packages.txt /tmp/packages.txt
COPY configs/deps/workstation-packages.txt /tmp/workstation-packages.txt
RUN apt-get update && \
    grep -hv '^[[:space:]]*#' /tmp/packages.txt /tmp/workstation-packages.txt | grep -hv '^[[:space:]]*$' | \
    xargs apt-get install -y

RUN apt-get install -y zsh wget && \
    wget -O /tmp/install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh && \
    chmod +x /tmp/install.sh && /tmp/install.sh && rm /tmp/install.sh

SHELL ["/bin/zsh", "-c"]

RUN git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

COPY docker/.zshrc /root/.zshrc

WORKDIR /workspace
CMD ["zsh"]
