services: 
  desktop:
    profiles: ["desktop"]
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /root/.gazebo/models/:/root/.gazebo/models/
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.Xauthority:/tmp/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

    cap_add:
      - SYS_PTRACE
    command: /bin/sh -c "while sleep 1000; do :; done"

    build:
      context: .
      dockerfile: Dockerfile.azure
    image: go2-lab:desktop
    container_name: desktop

    # run `cd .devcontainer/ && docker build . -t ros2-humble-dev:latest -f Dockerfile-humble`
    # to use the development environment, or you can build it with Dockerfile.
    # Perhaps Unitree will provide a dockerhub image later to save you time compiling.
    privileged: true
    network_mode: "host"
  jetson:
    profiles: ["jetson"]
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.slam
      network: host
    image: go2-lab:jetson
    container_name: jetson
    stdin_open: true
    tty: true

    privileged: true

    # --net=host
    network_mode: "host"

    # --ipc=host
    ipc: "host"

    # --shm-size=4gb
    shm_size: "4gb"

    # 旧docker-compose互換のGPU指定
    runtime: nvidia

    environment:
      NVIDIA_DRIVER_CAPABILITIES: "all"
      NVIDIA_VISIBLE_DEVICES: "all"
      DISPLAY: ${DISPLAY}
      RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
      ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-0}"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    working_dir: /workspace

    volumes:
      # ホストのディレクトリ構成をそのまま使う
      - ..:/workspace:cached

      # --volume=/data/LIDAR_dataset:/root/data
      - /data/LIDAR_dataset:/root/data

      # --volume=/tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    command: /bin/bash -lc "while sleep 1000; do :; done"
    
