x-common: &common
  network_mode: "host"
  command: /bin/zsh -c "while sleep 1000; do :; done"
  volumes:
    - ..:/workspace:cached
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  env_file: ../.env
  ipc: "host"

services:
  robot:
    <<: *common
    profiles: ["robot"]
    platform: linux/arm64
    build:
      context: ..
      dockerfile: docker/Dockerfile.robot
      args:
        BASE_IMAGE: ${ROBOT_BASE_IMAGE:-althack/ros2:humble-full}
      network: host
    image: go2-lab:robot
    container_name: robot
    runtime: nvidia

  workstation:
    <<: *common
    profiles: ["workstation"]
    build:
      context: ..
      dockerfile: docker/Dockerfile.workstation
      args:
        BASE_IMAGE: ${WORKSTATION_BASE_IMAGE:-althack/ros2:humble-full}
      network: host
    image: go2-lab:workstation
    container_name: workstation
